# Use the latest versions
invoker.goals = clean clover:setup verify clover:clover verifier:verify \
  -Dgroovy.eclipse.compiler=3.7.0 -Dgroovy.eclipse.batch=3.0.8-01 -Dgroovy.all=4.0.32

# Check also with generated sources
invoker.goals.1 = clean verify verifier:verify -Pwith-clover-setup-and-generated-sources \
  -Dverifier.verificationFile=src/test/verifier/verifications-generated.xml \
  -Dgroovy.eclipse.compiler=3.7.0 -Dgroovy.eclipse.batch=3.0.8-01 -Dgroovy.all=4.0.32
