name: A Test master on JDK11

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: temurin
        cache: maven

    - name: Run basic tests and install artifacts locally
      run: mvn clean install

    - name: Run integration tests
      run: mvn clean verify -Pintegration-tests
