name: A Test master on JDK8

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      commitHash:
        description: 'Commit'
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      if: inputs.commitHash == ''

    - uses: actions/checkout@v3
      if: inputs.commitHash != ''
      with:
        ref: '${{ inputs.commitHash }}'
      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: 8.0
        distribution: temurin
        cache: maven

    - name: Run basic tests and install artifacts locally
      run: mvn clean install

    - name: Run integration tests
      run: mvn clean verify -Pintegration-tests
